version: '3.9'

services:
  db:
    image: postgres:16
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 15s
      timeout: 10s
      retries: 5


  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: biomaterials_backend
    command: sh /biomaterials_backend/docker/app.sh
    ports:
      - 1222:8000
    depends_on:
      db:
        condition: service_healthy
